modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/ItsBlackGear/TheWildBackport-Master/issues"
license = "All Rights Reserved"

[[mods]]
    modId = "wildbackport"
    version = "${version}"
    displayName = "TheWildBackport"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/the-wild-backport"
    logoFile = "icon.png"
    authors = "BlackGear, Orcinus, Dopadream"
    description = '''Backport features from the wild update'''

[[dependencies.wildbackport]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.wildbackport]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,1.19)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.wildbackport]]
    modId="terrablender"
    mandatory=true
    versionRange="[1.0.0.59,)"
    ordering="NONE"
    side="BOTH"